// SPDX-License-Identifier: MIT
// DecompileList.java -- Ghidra headless postScript: decompile the functions named in a list file to C.
// Args: <out.c> <list>   list: one symbol name or hex address per line (# comments allowed), output in list order.
// Companion of ImportKallsymsRaw.java (raw RC2 kernel Image). The output is a decompilation of vendor code: do not redistribute.
import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.*;
import ghidra.program.model.address.*;
import java.io.*;
import java.nio.file.*;
import java.util.*;

public class DecompileList extends GhidraScript {
  public void run() throws Exception {
    String[] args = getScriptArgs();
    FunctionManager fm = currentProgram.getFunctionManager();
    List<Function> funcs = new ArrayList<>();
    for (String l : Files.readAllLines(Paths.get(args[1]))) {
      l = l.replaceAll("#.*", "").trim();
      if (l.isEmpty()) continue;
      Function f = null;
      if (l.matches("(0x)?[0-9a-fA-F]{8}")) {
        f = fm.getFunctionAt(currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(Long.decode(l.startsWith("0x") ? l : "0x" + l)));
      } else {
        for (Symbol s : currentProgram.getSymbolTable().getGlobalSymbols(l)) {
          f = fm.getFunctionAt(s.getAddress());
          if (f != null) break;
        }
      }
      if (f == null) printerr("DecompileList: no function " + l); else funcs.add(f);
    }
    DecompInterface d = new DecompInterface();
    DecompileOptions o = new DecompileOptions();
    o.grabFromProgram(currentProgram);
    d.setOptions(o);
    d.toggleCCode(true);
    d.toggleSyntaxTree(true);
    d.setSimplificationStyle("decompile");
    d.openProgram(currentProgram);
    PrintWriter pw = new PrintWriter(new FileWriter(args[0]));
    pw.println("/* Ghidra " + ghidra.framework.Application.getApplicationVersion()
        + " decompilation of the stock RC2 kernel Image (raw, VA = file offset + 0xc0408000), names from kallsyms."
        + " Generated by board/tools/DecompileList.java; objdump is the arbiter. */\n");
    for (Function f : funcs) {
      DecompileResults r = d.decompileFunction(f, 300, monitor);
      pw.println("// ===== " + f.getName() + " @ 0x" + f.getEntryPoint() + " (" + f.getBody().getNumAddresses() + " bytes)");
      if (r != null && r.decompileCompleted()) pw.println(r.getDecompiledFunction().getC());
      else pw.println("// decompile failed: " + (r == null ? "null" : r.getErrorMessage()));
    }
    pw.close();
    println("DecompileList: wrote " + funcs.size() + " functions to " + args[0]);
  }
}
